// =====================================================================
// Photo credits — generated by tools/sync-photos.py from img/credits.json
// =====================================================================

'use strict';

const PHOTO_CREDITS = [
  {
    "file": "img/products/ISO-003.jpg",
    "caption": "Staklena mineralna vuna",
    "title": "Glass wool insulation.jpg",
    "author": "Radomil at pl.wikipedia",
    "license": "CC BY-SA 3.0",
    "source": "wikimedia",
    "url": "https://commons.wikimedia.org/wiki/File:Glass_wool_insulation.jpg"
  },
  {
    "file": "img/products/ISO-007.jpg",
    "caption": "Ekstrudirani polistiren XPS",
    "title": "Styrodur.jpg",
    "author": "U.S. Army Corps of Engineers Europe District from Wiesbaden, Germany",
    "license": "Public domain",
    "source": "wikimedia",
    "url": "https://commons.wikimedia.org/wiki/File:Styrodur.jpg"
  },
  {
    "file": "img/products/ISO-004.jpg",
    "caption": "Ekspandirani polistiren EPS",
    "title": "Polistirolo.JPG",
    "author": "Phyrexian",
    "license": "CC BY-SA 3.0",
    "source": "wikimedia",
    "url": "https://commons.wikimedia.org/wiki/File:Polistirolo.JPG"
  },
  {
    "file": "img/products/CHM-006.jpg",
    "caption": "Vreće cementa",
    "title": "Close up of stacked cement bags",
    "author": "Ivan Radic",
    "license": "by 2.0",
    "source": "flickr",
    "url": "https://www.flickr.com/photos/26344495@N05/50550618521"
  },
  {
    "file": "img/products/ACC-003.jpg",
    "caption": "Bandaž traka i alat za gips ploče",
    "title": "Drywall and tools.jpg",
    "author": "Timothyjosephwood",
    "license": "CC BY-SA 4.0",
    "source": "wikimedia",
    "url": "https://commons.wikimedia.org/wiki/File:Drywall_and_tools.jpg"
  },
  {
    "file": "img/app/drywall-wall.jpg",
    "caption": "Gotov zid od gips ploča",
    "title": "Drywall.jpg",
    "author": "Amaxson at English Wikipedia",
    "license": "Public domain",
    "source": "wikimedia",
    "url": "https://commons.wikimedia.org/wiki/File:Drywall.jpg"
  },
  {
    "file": "img/app/drywall-room.jpg",
    "caption": "Soba obložena gips pločama",
    "title": "Scribed Plasterboard Ceiling - Strawbale House Build in Redm",
    "author": "Red Moon Sanctuary",
    "license": "by 2.0",
    "source": "flickr",
    "url": "https://www.flickr.com/photos/71646105@N03/8452210931"
  },
  {
    "file": "img/app/drywall-frame.jpg",
    "caption": "Montaža gips ploča na konstrukciju",
    "title": "DURING- 12 foot long sheets of drywall are installed on the",
    "author": "NLT CONSTRUCTION",
    "license": "by 2.0",
    "source": "flickr",
    "url": "https://www.flickr.com/photos/130832661@N04/16259621339"
  },
  {
    "file": "img/app/pallets-bags.jpg",
    "caption": "Palete sa vrećama na gradilištu",
    "title": "18 80lb bags of cement for the slab",
    "author": "mwilkie",
    "license": "by-sa 2.0",
    "source": "flickr",
    "url": "https://www.flickr.com/photos/41894170591@N01/3498456020"
  },
  {
    "file": "img/app/jointing.jpg",
    "caption": "Nanošenje mase za spojeve",
    "title": "Applying drywall joint compound",
    "author": "Georgia National Guard",
    "license": "by 2.0",
    "source": "flickr",
    "url": "https://www.flickr.com/photos/40994485@N04/5891937812"
  },
  {
    "file": "img/app/finishing.jpg",
    "caption": "Obrada spojeva gips ploča",
    "title": "Georgia Air Guard Civil Engineer",
    "author": "Georgia National Guard",
    "license": "by 2.0",
    "source": "flickr",
    "url": "https://www.flickr.com/photos/40994485@N04/5891371057"
  },
  {
    "file": "img/app/taping.jpg",
    "caption": "Bandažiranje plafona",
    "title": "180726-Z-IL540-1128",
    "author": "Minnesota National Guard",
    "license": "by 2.0",
    "source": "flickr",
    "url": "https://www.flickr.com/photos/45429509@N03/30058183198"
  }
];
