'use client'
import { useEffect, useMemo, useRef, useState } from 'react'
import { usePathname, useRouter, useSearchParams } from 'next/navigation'
import { CATEGORIES, PRICE_BANDS, PRODUCTS, SORTS, USES, filterProducts, type CategoryId, type Filters, type SortId, type UseId } from '@/lib/shop'
import { Flip, gsap, useGSAP } from '@/lib/gsap'
import { useShop } from '@/lib/cart'
import ProductCard from './ProductCard'
import ProductGlyph from '@/components/art/ProductGlyph'

type Extra = { brand:string; stock:boolean; view:'grid'|'list' }
const brands=[...new Set(PRODUCTS.map(p=>p.brand))]
function read(sp:URLSearchParams): Filters & Extra { return {query:sp.get('q')??'',category:(sp.get('kategorija')??'sve') as CategoryId|'sve',use:(sp.get('namjena')??'sve') as UseId|'sve',price:sp.get('cijena')??'sve',sort:(sp.get('sort')??'preporuceno') as SortId,onlySaved:false,brand:sp.get('brend')??'sve',stock:sp.get('stanje')==='da',view:sp.get('prikaz')==='lista'?'list':'grid'} }
function RollingCount({value}:{value:number}){const ref=useRef<HTMLSpanElement>(null),last=useRef(value);useGSAP(()=>{const n={value:last.current};gsap.to(n,{value,duration:.45,ease:'power2.out',onUpdate:()=>{if(ref.current)ref.current.textContent=String(Math.round(n.value))}});last.current=value},{scope:ref,dependencies:[value]});return <span ref={ref}>{value}</span>}
export default function CatalogClient(){
 const sp=useSearchParams(), router=useRouter(), path=usePathname(), {saved}=useShop(); const grid=useRef<HTMLDivElement>(null); const [mobile,setMobile]=useState(false); const [f,setF]=useState(()=>read(new URLSearchParams(sp.toString())))
 useEffect(()=>{const onPop=()=>setF(read(new URLSearchParams(window.location.search)));window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop)},[])
 const shown=useMemo(()=>filterProducts(f,saved).filter(p=>(f.brand==='sve'||p.brand===f.brand)&&(!f.stock||p.stock>0)),[f,saved])
 const update=(patch:Partial<typeof f>)=>{const state=grid.current?Flip.getState(grid.current.querySelectorAll('[data-flip-id]')):null; const next={...f,...patch};setF(next); const q=new URLSearchParams(); if(next.query)q.set('q',next.query);if(next.category!=='sve')q.set('kategorija',next.category);if(next.use!=='sve')q.set('namjena',next.use);if(next.price!=='sve')q.set('cijena',next.price);if(next.brand!=='sve')q.set('brend',next.brand);if(next.stock)q.set('stanje','da');if(next.sort!=='preporuceno')q.set('sort',next.sort);if(next.view==='list')q.set('prikaz','lista');router.replace(`${path}${q.size?'?'+q:''}`,{scroll:false});if(state)requestAnimationFrame(()=>Flip.from(state,{duration:.55,ease:'power3.inOut',absolute:true,stagger:.015}))}
 const reset=()=>update({...read(new URLSearchParams()),view:f.view}); const active=[f.category!=='sve'&&{key:'category',label:f.category,patch:{category:'sve'}},f.use!=='sve'&&{key:'use',label:f.use,patch:{use:'sve'}},f.price!=='sve'&&{key:'price',label:f.price,patch:{price:'sve'}},f.brand!=='sve'&&{key:'brand',label:f.brand,patch:{brand:'sve'}},f.stock&&{key:'stock',label:'na stanju',patch:{stock:false}},f.query&&{key:'query',label:`“${f.query}”`,patch:{query:''}}].filter(Boolean) as {key:string;label:string;patch:Partial<typeof f>}[]
 const controls=<div className="grid gap-3 md:grid-cols-4 xl:grid-cols-7"><input className="site-input md:col-span-2" value={f.query} onChange={e=>update({query:e.target.value})} placeholder="Pretraži naziv, SKU…"/><select className="site-select" value={f.category} onChange={e=>update({category:e.target.value as CategoryId|'sve'})}><option value="sve">Sve kategorije</option>{CATEGORIES.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="site-select" value={f.use} onChange={e=>update({use:e.target.value as UseId|'sve'})}><option value="sve">Sve namjene</option>{USES.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="site-select" value={f.price} onChange={e=>update({price:e.target.value})}><option value="sve">Sve cijene</option>{PRICE_BANDS.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select className="site-select" value={f.brand} onChange={e=>update({brand:e.target.value})}><option value="sve">Svi brendovi</option>{brands.map(x=><option key={x} value={x}>{x}</option>)}</select><select className="site-select" value={f.sort} onChange={e=>update({sort:e.target.value as SortId})}>{SORTS.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><button onClick={()=>update({stock:!f.stock})} className={`border-2 border-current px-3 py-3 font-mono text-[10px] uppercase ${f.stock?'bg-navy text-bg':''}`}>■ Na stanju</button></div>
 return <section id="artikli"><div className="sticky top-0 z-40 border-y-2 border-ink bg-bg/95 px-5 py-3 backdrop-blur md:top-0 md:px-[8.33vw]"><div className="flex items-center justify-between md:hidden"><button onClick={()=>setMobile(true)} className="border-2 border-ink px-4 py-3 font-mono text-[10px] uppercase">Filteri {active.length?`(${active.length})`:''}</button><span className="font-mono text-xs uppercase tabular-nums"><RollingCount value={shown.length}/> artikala</span></div><div className="hidden md:block">{controls}</div>{active.length>0&&<div className="mt-3 hidden flex-wrap gap-2 md:flex">{active.map(x=><button onClick={()=>update(x.patch)} key={x.key} className="border border-ink px-2 py-1 font-mono text-[9px] uppercase">■ {x.label} ×</button>)}<button onClick={reset} className="font-mono text-[9px] uppercase underline">Poništi sve</button></div>}</div>
 <div className="gutter py-10"><div className="mb-6 flex items-center justify-between"><p className="font-mono text-xs uppercase tabular-nums">Prikazano <RollingCount value={shown.length}/> / {PRODUCTS.length}</p><div className="flex border-2 border-ink font-mono text-[10px] uppercase"><button className={`px-3 py-2 ${f.view==='grid'?'bg-ink text-bg':''}`} onClick={()=>update({view:'grid'})}>Mreža</button><button className={`border-l-2 border-ink px-3 py-2 ${f.view==='list'?'bg-ink text-bg':''}`} onClick={()=>update({view:'list'})}>Lista</button></div></div>
 <div ref={grid} className={f.view==='grid'?'grid gap-5 sm:grid-cols-2 xl:grid-cols-3':''}>{shown.map(p=><ProductCard key={p.id} product={p} view={f.view}/>)}</div>{!shown.length&&<div className="grid min-h-[60vh] place-items-center border-2 border-ink p-8 text-center"><div><ProductGlyph product={PRODUCTS[0]} kind="hanger" className="mx-auto h-52"/><h2 className="text-title uppercase">Nema artikala.</h2><p className="mt-4 font-mono text-xs uppercase">Promijenite filtere ili pretragu.</p><button onClick={reset} className="mt-6 border-2 border-ink px-5 py-3 font-mono text-xs uppercase">Poništi sve</button></div></div>}</div>
 <div className={`fixed inset-0 z-[500] bg-navy p-5 text-bg transition-transform duration-500 md:hidden ${mobile?'translate-y-0':'translate-y-full'}`}><div className="flex justify-between border-b-2 border-bg pb-4"><strong className="uppercase">Filteri</strong><button onClick={()=>setMobile(false)} className="font-mono text-xs uppercase">Zatvori</button></div><div className="mt-6">{controls}</div><button onClick={()=>setMobile(false)} className="absolute inset-x-5 bottom-5 border-2 border-bg bg-bg px-4 py-4 font-mono text-xs uppercase text-ink">Prikaži {shown.length} artikala</button></div>
 </section>
}
