import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import PostArtDraw from '@/components/posts/PostArtDraw'
import ReadingProgress from '@/components/posts/ReadingProgress'
import TitleReveal from '@/components/posts/TitleReveal'
import ProductCard from '@/components/catalog/ProductCard'
import StepBand from '@/components/ui/StepBand'
import { POSTS, postBySlug } from '@/lib/posts'
import { PRODUCTS } from '@/lib/shop'
const id=(s:string)=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'dj').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')
const date=(x:string)=>new Intl.DateTimeFormat('bs-BA',{day:'2-digit',month:'long',year:'numeric'}).format(new Date(x))
export function generateStaticParams(){return POSTS.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:PageProps<'/objave/[slug]'>):Promise<Metadata>{const{slug}=await params;const p=postBySlug(slug);return p?{title:`${p.title} | Grand Company`,description:p.lead}:{title:'Objava nije pronađena'}}
export default async function ArticlePage({params}:PageProps<'/objave/[slug]'>){const{slug}=await params;const p=postBySlug(slug);if(!p)notFound();const heads=p.body.filter(b=>b.t==='h');const products=(p.skus??[]).flatMap(s=>{const x=PRODUCTS.find(q=>q.sku===s);return x?[x]:[]});const index=POSTS.indexOf(p),prev=POSTS[index-1],next=POSTS[index+1];return <article><ReadingProgress/><header className="gutter py-16 md:py-24"><p className="font-mono text-xs uppercase">{p.tag} · {date(p.date)} · {p.read} min čitanja</p><TitleReveal className="mt-8 max-w-[14ch] text-[clamp(50px,9vw,150px)] uppercase leading-[.84] tracking-[-.05em]" >{p.title}</TitleReveal><p className="mt-10 max-w-[50ch] text-xl uppercase leading-tight">{p.lead}</p></header><StepBand profile="diag-rev" tone="navy" className="gutter py-14"><PostArtDraw kind={p.art} title={p.title} className="mx-auto h-[45vh] max-w-5xl"/></StepBand><div className="gutter grid gap-12 py-24 md:grid-cols-[220px_minmax(0,720px)] md:justify-center"><aside className="hidden md:block"><div className="sticky top-24"><p className="font-mono text-[10px] uppercase opacity-60">U tekstu</p><nav className="mt-4 flex flex-col">{heads.map(h=><Link key={h.text} href={`#${id(h.text)}`} className="border-t border-ink py-3 font-mono text-[10px] uppercase">{h.text}</Link>)}</nav></div></aside><div className="article-copy">{p.body.map((b,i)=>{if(b.t==='h')return <h2 id={id(b.text)} key={i}>{b.text}</h2>;if(b.t==='p')return <p className="mt-6" key={i}>{b.text}</p>;if(b.t==='list')return <ul className="mt-6 space-y-3" key={i}>{b.items.map(x=><li key={x}>{x}</li>)}</ul>;if(b.t==='note')return <aside key={i} className="my-10 border-l-8 border-accent bg-navy p-6 text-bg"><p className="font-mono text-sm uppercase">Napomena</p><p className="mt-3">{b.text}</p></aside>;return <dl key={i} className="my-10 border-t-2 border-ink font-mono text-xs uppercase">{b.rows.map(([a,c])=><div key={a} className="grid grid-cols-[minmax(100px,1fr)_2fr] gap-4 border-b border-ink py-4"><dt>{a}</dt><dd>{c}</dd></div>)}</dl>})}</div></div>{products.length>0&&<section className="gutter pb-24"><p className="font-mono text-xs uppercase">Artikli iz teksta</p><h2 className="mt-5 text-title uppercase">Materijal za ovaj posao</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{products.slice(0,6).map(x=><ProductCard key={x.id} product={x} view="grid"/>)}</div></section>}<nav className="grid border-y-2 border-ink md:grid-cols-2">{prev?<Link href={`/objave/${prev.slug}`} className="p-8 md:p-16"><span className="font-mono text-xs uppercase">← Prethodna</span><strong className="mt-4 block text-3xl uppercase">{prev.title}</strong></Link>:<div/>}{next&&<Link href={`/objave/${next.slug}`} className="border-t-2 border-ink p-8 text-right md:border-l-2 md:border-t-0 md:p-16"><span className="font-mono text-xs uppercase">Sljedeća →</span><strong className="mt-4 block text-3xl uppercase">{next.title}</strong></Link>}</nav></article>}
