import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import ProductBuy from '@/components/catalog/ProductBuy'
import GlyphDraw from '@/components/catalog/GlyphDraw'
import ProductCard from '@/components/catalog/ProductCard'
import StepBand from '@/components/ui/StepBand'
import { DELIVERY_ZONES, STOCK_LABEL, WALL_SYSTEMS, stockLevel } from '@/gc/gc'
import { PRODUCTS, categoryName } from '@/lib/shop'

export function generateStaticParams(){return PRODUCTS.map(p=>({sku:p.sku}))}
export async function generateMetadata({params}:PageProps<'/prodavnica/[sku]'>):Promise<Metadata>{const{sku}=await params;const p=PRODUCTS.find(x=>x.sku===sku);return p?{title:`${p.name} | Grand Company`,description:p.desc}:{title:'Artikal nije pronađen'}}
export default async function ProductPage({params}:PageProps<'/prodavnica/[sku]'>){const{sku}=await params;const p=PRODUCTS.find(x=>x.sku===sku);if(!p)notFound();const systems=WALL_SYSTEMS.filter(s=>s.skus.includes(p.sku));const related=PRODUCTS.filter(x=>x.category===p.category&&x.id!==p.id).slice(0,3);const stock=stockLevel(p);return <>
 <div className="gutter py-7"><nav className="font-mono text-[10px] uppercase"><Link href="/prodavnica">Katalog</Link> / <Link href={`/prodavnica?kategorija=${p.category}`}>{categoryName(p.category)}</Link> / {p.sku}</nav></div>
 <section className="gutter grid gap-10 pb-24 md:grid-cols-[minmax(0,1.25fr)_minmax(340px,.75fr)]"><div><div className="relative grid min-h-[55vh] place-items-center border-2 border-ink bg-well"><GlyphDraw product={p} className="h-full max-h-[600px] w-full p-5 md:p-12"/><span className="absolute left-4 top-4 font-mono text-[10px] uppercase">← {p.spec.split(',')[0]} →</span><span className="absolute bottom-4 right-4 font-mono text-[10px] uppercase">{p.sku}</span></div><p className="mt-5 font-mono text-xs uppercase">{p.brand} · <i className="mr-2 inline-block size-2 bg-accent"/>{STOCK_LABEL[stock]}</p><h1 className="mt-5 text-[clamp(48px,7vw,120px)] uppercase leading-[.84] tracking-[-.045em]">{p.name}</h1><p className="mt-8 max-w-[48ch] text-xl uppercase leading-tight">{p.desc}</p></div><ProductBuy product={p}/></section>
 <StepBand profile="valley" tone="navy" className="gutter py-20"><div className="grid gap-12 md:grid-cols-2"><div><p className="font-mono text-xs uppercase text-accent">Tehnički podaci</p><dl className="mt-6 font-mono text-xs uppercase">{[['SKU',p.sku],['Brend',p.brand],['Specifikacija',p.spec],['Masa',`${p.weight} kg / prodajna jedinica`],['Kategorija',categoryName(p.category)]].map(([a,b])=><div key={a} className="grid grid-cols-[120px_1fr] border-t border-bg/30 py-4"><dt className="opacity-60">{a}</dt><dd>{b}</dd></div>)}</dl></div><div><p className="font-mono text-xs uppercase text-accent">Dostava i istovar</p><p className="mt-6 max-w-[38ch] text-2xl uppercase">Za teže i paletne isporuke dostupan je istovar kranom. Termin i pristup potvrđuju se uz ponudu.</p><ul className="mt-6 font-mono text-[10px] uppercase">{DELIVERY_ZONES.map(z=><li key={z.id} className="border-t border-bg/30 py-3">{z.label} · standard {z.standard} KM · kran transport {z.kranTransport} KM + rad {z.kranWork} KM</li>)}</ul></div></div></StepBand>
 <section className="gutter py-24"><div className="grid gap-12 md:grid-cols-2"><div><p className="font-mono text-xs uppercase">Koristi se za</p><div className="mt-5 flex flex-wrap gap-2">{p.uses.map(u=><Link key={u} href={`/prodavnica?namjena=${u}`} className="border-2 border-ink px-4 py-3 font-mono text-xs uppercase">■ {u.replaceAll('-',' ')}</Link>)}</div></div><div><p className="font-mono text-xs uppercase">Sistemi</p>{systems.length?<ul className="mt-5">{systems.map(s=><li key={s.code} className="border-t-2 border-ink py-4"><strong className="text-2xl uppercase">{s.code} · {s.name}</strong><p className="mt-2 font-mono text-[10px] uppercase opacity-60">{s.build}</p></li>)}</ul>:<p className="mt-5 uppercase">Artikal nije vezan za zidni sistem iz kataloga.</p>}</div></div><h2 className="mt-28 text-title uppercase">Povezani artikli</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{related.map(x=><ProductCard key={x.id} product={x} view="grid"/>)}</div></section>
 </>}
