#!/usr/bin/env python3
"""Rebuild the product photo map and the credits module.

Drop product photos into img/products/ named after the article code
(KNF-001.jpg, CHM-004.jpg …) and run:  python3 tools/sync-photos.py
"""
import json, os, re, sys

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(root)

skus = sorted(f[:-4] for f in os.listdir('img/products') if f.lower().endswith(('.jpg', '.jpeg', '.png', '.webp')))
files = {s: next(f'img/products/{s}{ext}' for ext in ('.jpg', '.jpeg', '.png', '.webp') if os.path.exists(f'img/products/{s}{ext}')) for s in skus}
mapping = ',\n'.join(f"  '{s}': '{p}'" for s, p in files.items())

data = open('js/data.js', encoding='utf-8').read()
data = re.sub(r'const PRODUCT_PHOTOS = \{.*?\n\};', 'const PRODUCT_PHOTOS = {\n' + mapping + ',\n};', data, flags=re.S)
open('js/data.js', 'w', encoding='utf-8').write(data)

if os.path.exists('img/credits.json'):
    credits = json.load(open('img/credits.json'))
    header = ("// =====================================================================\n"
              "// Photo credits — generated by tools/sync-photos.py from img/credits.json\n"
              "// =====================================================================\n\n'use strict';\n\n")
    open('js/credits.js', 'w', encoding='utf-8').write(header + 'const PHOTO_CREDITS = ' + json.dumps(credits, ensure_ascii=False, indent=2) + ';\n')

print(f'Povezano {len(files)} fotografija proizvoda: {", ".join(files) or "nijedna"}')
